apiVersion: v2
name: rainbond-operator
description: Goodrain rainbond-operator Helm chart for Kubernetes
type: application
version: cloud-1.3.0
appVersion: 5.3.0-cloud
home: https://github.com/goodrain/rainbond-operator
sources:
  - https://github.com/goodrain/rainbond-operator
